# Generated by Django 5.1.2 on 2024-12-05 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('Id_Vuelo', models.AutoField(primary_key=True, serialize=False)),
                ('Id_Empleado', models.CharField(max_length=100)),
                ('Numero_Vuelo', models.CharField(max_length=100)),
                ('Origen', models.CharField(max_length=100)),
                ('Destino', models.CharField(max_length=100)),
                ('Hora_llegada', models.TimeField()),
                ('Hora_Salida', models.TimeField()),
                ('Estado_Vuelo', models.CharField(max_length=100)),
            ],
        ),
    ]
