# Generated by Django 5.1.2 on 2024-12-05 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('Id_Boleto', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Id_Reserva', models.CharField(max_length=100)),
                ('Numero_Boleto', models.CharField(max_length=100)),
                ('Precio', models.CharField(max_length=100)),
                ('Fecha_Emicion', models.CharField(max_length=100)),
                ('Estado_Boleto', models.CharField(max_length=100)),
                ('Clase_Servicio', models.CharField(max_length=100)),
            ],
        ),
    ]
