# Generated by Django 5.1.2 on 2024-12-05 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('Id_Avion', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('Modelo', models.CharField(max_length=100)),
                ('Aerolinea', models.CharField(max_length=100)),
                ('Capacidad_Asientos', models.IntegerField()),
                ('Capacidad_Carga', models.IntegerField()),
                ('Año_Fabricacion', models.CharField(max_length=4)),
                ('Estado_Avion', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
