# Generated by Django 5.1 on 2024-12-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('Id_Reserva', models.AutoField(primary_key=True, serialize=False)),
                ('Id_pasajero', models.CharField(max_length=100)),
                ('Id_vuelo', models.CharField(max_length=100)),
                ('Fecha_Reserva', models.DateField()),
                ('Estado_reserva', models.CharField(max_length=100)),
                ('Clase_Servicio', models.CharField(max_length=100)),
                ('Numero_Reserva', models.CharField(max_length=100)),
            ],
        ),
    ]
