# Generated by Django 5.1.2 on 2024-12-05 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('Id_Pago', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Id_Pasagero', models.CharField(max_length=100)),
                ('Id_Empleado', models.CharField(max_length=100)),
                ('Id_Vuelo', models.CharField(max_length=100)),
                ('Id_Boleto', models.CharField(max_length=100)),
                ('Precio', models.CharField(max_length=100)),
                ('Fecha_Pago', models.CharField(max_length=100)),
                ('Metodo_Pago', models.CharField(max_length=100)),
                ('Estado', models.CharField(max_length=100)),
            ],
        ),
    ]
